export default imageData=[
    {
        key:1,
        path:'../assets/images/jesus1.png'
    },
    {
        key:2,
        path:'../assets/images/jesus2.png'
    },
    {
        key:3,
        path:'../assets/images/jesus3.png'
    },
    {
        key:4,
        path:'../assets/images/jesus4.png'
    },
    {
        key:5,
        path:'../assets/images/jesus5.png'
    },
    {
        key:6,
        path:'../assets/images/jesus6.png'
    },
    {
        key:7,
        path:'../assets/images/jesus7.png'
    },
    {
        key:8,
        path:'../assets/images/jesus8.png'
    },
    {
        key:9,
        path:'../assets/images/jesus9.png'
    },
    {
        key:10,
        path:'../assets/images/jesus10.png'
    },
]
